#import "./ImageFragment.gql"
#import "./VideoFragment.gql"

fragment RecipeFragmentLight on RecipeRecord {
	__typename
	_modelApiKey
	id
	title
	intro(markdown: false)
	image {
		...ImageThumbnailFragment
	}
	slug
}
